site_name: Web Development Lab Documentation
site_description: Documentation for Labs 1-4
theme: readthedocs

nav:
  - Home: index.md
  - Lab 1:
    - Work 1: lab1/work1.md
    - Work 2: lab1/work2.md
    - Work 3: lab1/work3.md
    - Work 4: lab1/work4.md
    - Work 5: lab1/work5.md
  - Lab 2:
    - Overview: lab2/overview.md
    - Models: lab2/models.md
    - Views: lab2/views.md
    - Forms: lab2/forms.md
    - Admin: lab2/admin.md
    - URLs: lab2/urls.md
  - Lab 3:
    - Models: lab3/models.md
    - Views: lab3/views.md
    - Forms: lab3/forms.md
    - Admin: lab3/admin.md
    - URLs: lab3/urls.md
    - Practical: lab3/practical.md
    - LeetCode: lab3/leetcode.md
  - Lab 4:
    - Pages: lab4/pages.md
    - Components: lab4/components.md

markdown_extensions:
  - toc:
      permalink: true
